-- AlterTable
ALTER TABLE "City" ALTER COLUMN "localWealth" SET DEFAULT 0,
ALTER COLUMN "localWealth" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Resource" ALTER COLUMN "currency" SET DEFAULT 0,
ALTER COLUMN "currency" SET DATA TYPE DOUBLE PRECISION;
